INSERT INTO airline(name, website) VALUES ('Belle Air','www.belleair.it');
INSERT INTO airline(name, website) VALUES ('Wizz Air','www.wizzair.com');
INSERT INTO airline(name, website) VALUES ('InterSky','www.intersky.biz');
INSERT INTO airline(name, website) VALUES ('Jetairfly','www.jetairfly.com');
INSERT INTO airline(name, website) VALUES ('SmartWings','www.smartwings.com');
INSERT INTO airline(name, website) VALUES ('Cimber Sterling','www.cimber.com');
INSERT INTO airline(name, website) VALUES ('XL Airways France','www.xlairways.fr');
INSERT INTO airline(name, website) VALUES ('Vueling','www.vueling.com');
INSERT INTO airline(name, website) VALUES ('Germanwings','www.germanwings.com');
INSERT INTO airline(name, website) VALUES ('TUlfly','www.tuifly.com');
INSERT INTO airline(name, website) VALUES ('Ryanair','www.ryanair.com');
INSERT INTO airline(name, website) VALUES ('LOT','www.lot.com');
INSERT INTO airline(name, website) VALUES ('Air Moldova','www.airmoldova.md'); 
INSERT INTO airline(name, website) VALUES ('Eurowings','www.Eurowings.com');
INSERT INTO airline(name, website) VALUES ('Austrian','www.eurowings.com');
INSERT INTO airline(name, website) VALUES ('Aeroflot','www.aeroflot.ru/ru-en'); 
INSERT INTO airline(name, website) VALUES ('Belavia','www.belavia.by');
INSERT INTO airline(name, website) VALUES ('atlasglobal','www.atlasglb.com');
INSERT INTO airline(name, website) VALUES ('airberlin','www.airberlin.com');
INSERT INTO airline(name, website) VALUES ('British Airways','www.britishairways.com');
INSERT INTO airline(name, website) VALUES ('Lufthansa','www.lufthansa.com');
INSERT INTO airline(name, website) VALUES ('Lufthansa CityLine','www.lufthansa.com');
