INSERT INTO airport (airportcode, airportname, cityid) VALUES ('GDN','Gdańsk', 1);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('WAW','Warszawa - Lotnisko Chopina', 2);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('WMI','Warszawa - Modlin', 2);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('KRK','Kraków', 3);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('KTW','Katowice', 4);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('WRO','Wrocław', 5);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('SZZ','Szczecin', 6);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('HAM','Hamburg', 7);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('HAJ','Hanover', 8);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('FRA','Frankfurt', 9);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('CGN','Kolonia/Bonn', 10);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('STR','Stuttgart', 11);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('BER','Berlin-Brandenburg', 12);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('SXF','Berlin-Schonefeld', 12);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('DUS','Dusseldorf', 13);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('MUC','Monachium', 14);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('SXB','Strasburg', 15);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('PAR','Paryż', 16);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('BVA','Paryż - Beauvais Tille', 16);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('ORY','Paryż - Orly', 16);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('CDG','Paryż - Roissy-Charles de Gaulle', 16);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('NTE','Nantes', 17);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('BOD','Bordeaux-Merignac', 18);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('TLS','Tuluza-Blagnac', 19);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('LYS','Lyon-Saint-Exupury', 20);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('GNB','Grenoble-Isere', 21);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('MRS','Marsylia', 22);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('LIL','Lille-Lesquin', 23);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('NCE','Nicea-Lazurowe Wybrzeże', 24);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('LCY','Londyn - City', 25);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('LGW','Londyn-Gatwick', 25);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('STN','Londyn-Stansted', 25);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('LTN','Londyn-Luton', 25);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('LHR','Londyn-Heathrow', 25);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('SEN','Londyn-Southend', 25);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('NWI','Norwich  ', 26);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('SOU','Southampton', 27);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('CWL','Cardiff', 28);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('BHX','Birmingham', 29);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('EMA','Nottingham - East Midlands', 30);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('LPL','Liverpool-John Lennon', 31);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('MAN','Manchester', 32);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('LBA','Leeds/Bradford', 33);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('NCL','Newcastle', 34);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('EDI','Edynburg', 35);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('GLA','Glasgow', 36);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('ABZ','Aberdeen', 37);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('INV','Inverness', 38);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('DUB','Dublin', 39);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('ORK','Cork', 40);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('SNN','Shannon', 41);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('BFS','Belfast-International', 42);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('SVO','Moskwa-Szeremietiewo', 43);
INSERT INTO airport (airportcode, airportname, cityid) VALUES ('LIS','Lizbona', 44);


